server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019
    username: root
    password: sa1234

#    schema:
#      - classpath:sql/payment.sql
eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #clent端向server端发送心跳改为每秒一次
    lease-expiration-duration-in-seconds: 2 #没有心跳了只等2秒没有就挂

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bdqn.springcloud.entities


