server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  #      defaultZone: http://eureka7002.com:7002/eureka/  #集群
#  server:
#    enable-self-preservation: false #关闭eureka自我保护机制
#    eviction-interval-timer-in-ms: 2000
#  server:
#    # 关闭自我保护机制，保证不可用服务被及时剔除
#    #  # 清理间隔（单位毫秒，默认是60*1000）
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000

